// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerStatisticsModel.Configurations;

#nullable disable

namespace PlayerStatisticsModel.Migrations
{
    [DbContext(typeof(PlayerStatsDbContext))]
    partial class PlayerStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PlayerStatisticsModel.Entities.UserStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.Property<int>("DuelsDrawn")
                        .HasColumnType("int")
                        .HasColumnName("DUELS_DRAWN");

                    b.Property<int>("DuelsLost")
                        .HasColumnType("int")
                        .HasColumnName("DUELS_LOST");

                    b.Property<int>("DuelsPlayed")
                        .HasColumnType("int")
                        .HasColumnName("DUELS_PLAYED");

                    b.Property<int>("DuelsWon")
                        .HasColumnType("int")
                        .HasColumnName("DUELS_WON");

                    b.Property<DateTime>("LastPlayedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LAST_PLAYED_AT");

                    b.HasKey("Id");

                    b.ToTable("USER_STATISTICS");
                });
#pragma warning restore 612, 618
        }
    }
}
